AllCops:
  NewCops: enable

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120
  Severity: refactor

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
  AllowedMethods:
    - bamboo_xml
    - bamboo_json

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MutableConstant:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/EmptyElse:
  EnforcedStyle: empty

Style/AsciiComments:
  Enabled: false
