language: minimal

services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose run web rubocop
  - docker-compose run web bundle audit --update
  - docker-compose run web rspec
  - docker-compose -f docker-compose.test.yml run web rspec
