version: '3'
services:
  web:
    build: .
    command: rerun --background 'ruby app.rb'
    volumes:
      - .:/app
    ports:
      - 1500:1500
    depends_on:
      - redis
    environment:
      - REDIS_ENABLED=true
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis:5.0.8
    ports:
      - 6379:6379
  cache:
    image: nginx:1.17.9
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./tmp/nginx:/var/cache/nginx
    ports:
      - 1501:1501
    depends_on:
      - web
